"""
Configuration file for test resource sizes and shared gene counts.
This file is automatically generated by running update_resource_sizes.py.
Do not edit manually; rerun update_resource_sizes.py to update values.
"""

# Resource sizes for hg19 data
RESOURCE_SIZES = {"knownGene_hg19": 381987, "kgXref_hg19": 381943, "cytoBand_hg19": 862}

# Shared gene counts for specific test cases
SHARED_GENE_COUNTS = {
    "default": {"len1": 16272, "len2": 16272},
    "1000G": {"len1": 8746},
    "X_chrom_male": {"len1": 278, "len2": 11432},
    "X_chrom_female": {"len1": 11432, "len2": 11432},
}
